exp_name: vanilla_GPT
evaluate: false
pred:
    model: gpt
    generate: false
    from_file: true
    path: gen_pred_gpt.csv
    out_path: gen_pred_gpt.csv

expl:
    model: gpt
    generate: true
    from_file: false
    out_path: gen_expl_gpt.csv
