exp_name: vanilla_MedGPT
evaluate: false
pred:
    model: medgpt
    generate: true
    from_file: false
    out_path: gen_pred_med.csv

expl:
    model: medgpt
    generate: true
    from_file: false
    out_path: gen_expl_med.csv

medgpt:
    model_args:
        cfg_path: configs/minigpt/default.yaml
        gpu_id: 0
        options: None
    prompt_args:
        temperature: 0.6
        top_p: 0.9
        mode: caption
