exp_name: no_context_qwen
evaluate: false
pred:
    model: qwen
    generate: true
    from_file: false
    path: None
    out_path: qwen_pred.csv

expl:
    model: qwen
    generate: true
    from_file: false
    out_path: gen_expl_qwen_no_ctxt.csv
    no_ctxt: true
