exp_name: vanilla_qwen
evaluate: false
pred:
    model: qwen
    generate: false
    from_file: true
    path: gen_pred_qwen.csv
    out_path: None

expl:
    model: qwen
    generate: true
    from_file: false
    out_path: gen_expl_qwen.csv
    no_ctxt: false
